stages:
- stage: Compliance
  jobs:
  - job: 
    steps:
    - task: ComponentGovernanceComponentDetection@0
      inputs:
        scanType: 'Register'
        verbosity: 'Verbose'
        alertWarningLevel: 'High'

- stage: Accumulo Spark 
  jobs:
  - job:
    pool: 
      vmImage: 'ubuntu-16.04'
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'spark/pom.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        goals: 'package'
        options: '-B' # batch mode for non-interactive release
      displayName: 'Accumulo Spark components'

