pr:
- master

stages:
- stage: Compliance
  jobs:
  - job: 
    steps:
    - task: ComponentGovernanceComponentDetection@0
      inputs:
        scanType: 'Register'
        verbosity: 'Verbose'
        alertWarningLevel: 'High'

- stage: AccumuloSparkConnector
  jobs:
  - job:
    pool: 
      vmImage: 'ubuntu-16.04'
    steps:
    - task: Maven@3
      displayName: 'Accumulo Spark Connector components'
      inputs:
        mavenPomFile: 'connector/pom.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        goals: 'package'
        options: '-B' # batch mode for non-interactive release

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: connector/iterator/target/accumulo-spark-iterator-1.0.0-SNAPSHOT-shaded.jar
        artifactName: accumulo-spark-iterator

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: connector/datasource/target/accumulo-spark-datasource-1.0.0-SNAPSHOT-shaded.jar
        artifactName: accumulo-spark-datasource


       

