name: Java CI

on: [push]

env:
  AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_KEY  }}
  
jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    
    - name: Build with Maven
      working-directory: connector
      run: mvn -B package
        
    - name: Copy jars to Blob Storage
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az storage blob upload-batch -d connector/datasource/target --pattern *-shaded.jar -c accumulo-spark-jars
          az storage blob upload-batch -d connector/iterator/target --pattern *-shaded.jar -c accumulo-spark-jars
