name: Java CI

on: [push]
  
jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    
    - name: Build with Deploy Maven
      working-directory: connector
      run: mvn -B package deploy
